training_parameters:
  epochs: 2
  learning_rate: 0.0001
dataloader_parameters:
  train_csv: ./data/metadata/metadata.csv
  val_csv: ./data/metadata/metadata.csv
  root_dir: ./data/videos
  batch_size: 4
  max_frames: 69
  num_workers: 4
  pin_memory: True
model_parameters:
  rnn_type: lstm
  rnn_layers: 2
  rnn_hidden: 100
  trainable_backbone: false
  heads_params:
    byrt: [2, 2]
    byrn: [2, 2]
    bdrt: [2, 2]
    bdrn: [2, 2]
    ft: [2, 2]
    fn: [2, 2]
    landed: [2, 2]
    stance: [2, 2]
